version: '{branch}.{build}'
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
    dotnet restore CertBuilder.csproj --verbosity m;
    dotnet restore Tests/CertBuilderTests.csproj --verbosity m;
build:
  project: CertBuilder.csproj
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: dotnet test Tests/CertBuilderTests.csproj --test-adapter-path:. --logger:Appveyor
deploy:
- provider: NuGet
  api_key:
    secure: 6GvZa7o2zpkm0HpT7yizpCa2x8vMXeCqmNR162XVBrxDUjm3rtgADvyrO5+tr8Hy
  on:
    APPVEYOR_REPO_TAG: true
